### ISSUE TITLE
🐛 Bug: [secret-messages] project-level tsc fails

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [LearningTypeScript/projects#338]
### Bug Report Checklist

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have pulled the latest `main` branch of the repository.
- [x] I have [searched for related issues](https://github.com/LearningTypeScript/projects/issues?q=is%3Aissue+label%3A%22type%3A+bug%22) and found none that matched my issue.
- [x] This is the appropriate issue form for the bug I would like to report.

### Expected

`npm run tsc` in `secret-messages` should pass. `check-solutions.sh "tsc"` runs it in every project.

### Actual

It fails, and has since #82:

```
02-allowed-imports/index.ts(1,20): error TS7016: Could not find a declaration file for module './answer.js'.
02-allowed-imports/index.ts(2,26): error TS2732: Cannot find module './guesses.json'.
02-allowed-imports/index.ts(8,33): error TS2532: Object is possibly 'undefined'.
```

It's the only one of the 30 projects that fails. Unnoticed because the all-projects sweep only runs when a PR touches no `projects/**` files.

### Impacted Project

configuration-options/secret-messages

### Additional Info

A project-level `tsc` never reads step TSConfigs, so `allowJs` and `resolveJsonModule` are missing, and `message.codePointAt(i)` is `number | undefined` under `strict`. Blocks #337.
